syntax = "proto3";

option java_multiple_files = true;
option java_package = "edu.eci.arsw.wellness.gym";
option java_outer_classname = "GymProto";

message GymBookingRequest {
    string student_id = 1;
    string day = 2;
    string time_slot = 3;
}

message GymBookingResponse {
    bool success = 1;
    string message = 2;
    string session_id = 3;
}

message GymStudentRequest {
    string student_id = 1;
}

message GymSession {
    string id = 1;
    string student_id = 2;
    string day = 3;
    string time_slot = 4;
}

message SessionList {
    repeated GymSession sessions = 1;
}

service GymService {
    rpc BookSession(GymBookingRequest) returns (GymBookingResponse);
    rpc GetSessions(GymStudentRequest) returns (SessionList);
}
